name: pylon
description: "Anchor data in your widget tree & obtain them more reliably than provider."
version: 3.1.0
repository: https://github.com/ArcaneArts/pylon
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  fast_log: ^1.0.7
  universal_html: ^2.2.4
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  toxic: '>=1.3.1 <1.4.0'
  toxic_flutter: '>=1.0.1 <2.0.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
